### ISSUE TITLE
"New Bug": include test path into tester-run option

### ISSUE THREAD

**Issue by okt-romanzh** [ts-factory/bublik-ui#173]
In "New Bug" button I see:
```
Hash: 06dee388e778c7024fb43b7aa9cd24c0
Path: `/rdma-compl-ts/rdma_unit_test/unit/AhTest/CreateAndDestroy`
CMD: `./run.sh --cfg=dellr7515s-salina --tester-run=06dee388e778c7024fb43b7aa9cd24c0 -n`
```
According to dispatcher.sh help hash is used to select an iteration and we still need to provide test path so CMD should has
--tester-run=<path>%<hash>:
```
CMD: `./run.sh --cfg=dellr7515s-salina --tester-run=rdma-compl-ts/rdma_unit_test/unit/AhTest/CreateAndDestroy%06dee388e778c7024fb43b7aa9cd24c0 -n`
```

Note: <path> shouldn't start from `/`

**Comment by okt-limonikas** [comment]
@okt-romanzh 

For this link https://ts-factory.io/bublik/v2/log/2714022?mode=treeAndlog&focusId=2714026

It should generate this, correct?
CMD: `./run.sh --cfg=balin-x710-p0 --tester-run=dpdk-ethdev-ts/usecases/x_burst_simple%23422608f6424b199f2e76bfd58b2fb5 -n`
