### ISSUE TITLE
"Run" page: show the difference between PASSED columns

### ISSUE THREAD

**Issue by okt-romanzh** [ts-factory/bublik-ui#175]
![Screenshot 2024-10-21 at 18 53 29](https://github.com/user-attachments/assets/8a78df85-02c6-4aa6-8043-2a2b96a64801)
On "Run" page we have 2 PASSED and 2 FAILED columns. It's not clear what's the difference between them.
We need to show the difference by text, not color or icons. Maybe OK/NOK or something like this

**Comment by okt-kostik** [comment]
There is a reasonable complain from some of the team members.

Any idea what can be done?

**Comment by okt-limonikas** [comment]
My suggestion is to group them together and add header above with "Expected"/"Unexpected" label
Maybe add icon and or better header label

Here's rough draft:
Order messed up

![brave_screenshot_localhost (1)](https://github.com/user-attachments/assets/47365db4-2c7e-4c0d-ad54-3e9896e5c255)
