### ISSUE TITLE
Unify the format of field names in the history search form

### ISSUE THREAD

**Issue by ol-nata** [ts-factory/bublik-ui#34]
In the history search form, field names identical in data type use different forms of nouns (some use the plural, and some use the singular). I suggest using the format `Parameters - Parameter expression`, `Branches - Branch expression` ...
Like this:

![2c4eabcd-3329-4449-afbf-653d0b9ad1c0](https://github.com/ts-factory/bublik-ui/assets/114595469/cbadb7ea-1794-4118-a950-cee7d5803cb1)

**Comment by okt-limonikas** [comment]
Fixed in #85
