### ISSUE TITLE
Log: verdicts and artifacts are not displayed on the pages

### ISSUE THREAD

**Issue by ol-nata** [ts-factory/bublik-ui#63]
It is necessary that verdicts and artifacts are always displayed. They are currently displayed in the "All pages" mode and are not displayed on the pages.

1 page:
![image](https://github.com/ts-factory/bublik-ui/assets/114595469/f619c152-2375-4961-9dcf-baeb3323566f)

All pages:
![image](https://github.com/ts-factory/bublik-ui/assets/114595469/d270741b-51e9-49cf-aba4-8aa6da057c96)

**Comment by okt-limonikas** [comment]
Now all artifacts and verdicts should be displayed on all pages
