### ISSUE TITLE
Log: the second page does not open

### ISSUE THREAD

**Issue by ol-nata** [ts-factory/bublik-ui#65]
An error occurs when trying to open the second page of the log:
![image](https://github.com/ts-factory/bublik-ui/assets/114595469/38fd1ab5-778a-4bfb-b300-f24c3dbeda9d)
![image](https://github.com/ts-factory/bublik-ui/assets/114595469/0f76d200-5144-4618-ae7f-068aed06323a)

**Comment by okt-limonikas** [comment]
Should be fixed
